[Variables]

; ---------------------------------------- General

Player=Web

Color=43,48,59,255
Font=Pacifico

Round=1

; ---------------------------------------- Scale

AScale=0.7
BScale=1
PScale=1

; ---------------------------------------- Cover Art

BorderCA=1

; ---------------------------------------- Progress Bar

BorderPG=1
PosColor=30,30,30

; ---------------------------------------- Track Info

Size =20
Align=Left

; ---------------------------------------- Visualizer

Bars=39
BarWidth=25
BarHeight=290
BarSpacing=2

; ---------------------------------------- Circles

PPCircle=0
PRCircle=0
NXCircle=0
