[MeterRotator1]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator2]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator3]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator4]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator5]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator6]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator7]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator8]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator9]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator10]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator11]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator12]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator13]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator14]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator15]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator16]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator17]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator18]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator19]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator20]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator21]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator22]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator23]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator24]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator25]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator26]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator27]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator28]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator29]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator30]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator31]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator32]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator33]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator34]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator35]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator36]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator37]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator38]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator39]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator40]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator41]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator42]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator43]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator44]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator45]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator46]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator47]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator48]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator49]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator50]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator51]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator52]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator53]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator54]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator55]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator56]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator57]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator58]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator59]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator60]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator61]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator62]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator63]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator64]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator65]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator66]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator67]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator68]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator69]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator70]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator71]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator72]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator73]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator74]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator75]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator76]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator77]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator78]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator79]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator80]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator81]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator82]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator83]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator84]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator85]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator86]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator87]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator88]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator89]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator90]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator91]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator92]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator93]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator94]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator95]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator96]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator97]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator98]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator99]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator100]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator101]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator102]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator103]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator104]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator105]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator106]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator107]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator108]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator109]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator110]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator111]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator112]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator113]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator114]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator115]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator116]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator117]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator118]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator119]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator120]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator121]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator122]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator123]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator124]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator125]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator126]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator127]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator128]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator129]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator130]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator131]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator132]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator133]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator134]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator135]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator136]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator137]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator138]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator139]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator140]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator141]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator142]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator143]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator144]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator145]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator146]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator147]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator148]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator149]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator150]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator151]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator152]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator153]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator154]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator155]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator156]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator157]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator158]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator159]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator160]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator161]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator162]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator163]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator164]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator165]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator166]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator167]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator168]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator169]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator170]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator171]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator172]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator173]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator174]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator175]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator176]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator177]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator178]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator179]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator180]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator181]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator182]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator183]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator184]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator185]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator186]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator187]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator188]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator189]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator190]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator191]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator192]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator193]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator194]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator195]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator196]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator197]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator198]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator199]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator200]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator201]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator202]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator203]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator204]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator205]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator206]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator207]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator208]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator209]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator210]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator211]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator212]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator213]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator214]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator215]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator216]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator217]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator218]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator219]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator220]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator221]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator222]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator223]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator224]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator225]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator226]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator227]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator228]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator229]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator230]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator231]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator232]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator233]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator234]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator235]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator236]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator237]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator238]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator239]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator240]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator241]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator242]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator243]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator244]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator245]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator246]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator247]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator248]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator249]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator250]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator251]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator252]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator253]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator254]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator255]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator256]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator257]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator258]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator259]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator260]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator261]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator262]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator263]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator264]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator265]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator266]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator267]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator268]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator269]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator270]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator271]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator272]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator273]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator274]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator275]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator276]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator277]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator278]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator279]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator280]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator281]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator282]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator283]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator284]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator285]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator286]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator287]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator288]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator289]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator290]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator291]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator292]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator293]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator294]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator295]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator296]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator297]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator298]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator299]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator300]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator301]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator302]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator303]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator304]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator305]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator306]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator307]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator308]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator309]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator310]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator311]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator312]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator313]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator314]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator315]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator316]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator317]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator318]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator319]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator320]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator321]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator322]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator323]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator324]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator325]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator326]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator327]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator328]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator329]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator330]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator331]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator332]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator333]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator334]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator335]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator336]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator337]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator338]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator339]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator340]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator341]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator342]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator343]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator344]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator345]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator346]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator347]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator348]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator349]
Meter=Rotator
MeasureName=MeasureZero

[MeterRotator350]
Meter=Rotator
MeasureName=MeasureZero