[Variables]

skinSize=350
lastSetWidth=350

Player=iTunes
alignRight=0

activePlugin=NowPlaying

topTextWidth=551
bottomTextWidth=160

; 0 = MUSIC, 2 = WEBNOWPLAYING
MusicSwitch=0
playerController=Title0
currentlySetName=iTunes
currentlySetPlayer=WMP

adaptiveHideActive=0

stowAway=0
stowAwayName=NULL

topText=mArtist
bottomText=mTitle

disableScroll=0

removeExtraFromText=1

thinFont=Metropolis Extra Light
thickFont=Metropolis Medium
controlsFont=Metropolis Medium

mediaTextPositionHor=0
mediaTextAlignment=LeftBottom
mediaTextAlignmentPure=Left
interfaceTextAlignment=Right
nowTextPositionHor=64.75
hairlinePositionHor=75.25
topTextPositionHor=86.625
playCtrlPositionHor=35
settingsTextPositionHor=40.25
indicatorPositionHor=24.5
indicatorPositionHorPure=14
conflictIndicatorPositionHor=10.5
conflictIndicatorPositionHorPure=28
